// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMpQzpKIEt7p4c1_sjOh8fw622J5AUlZg',
    appId: '1:908484753448:web:171cc0d22d83665cbe5d1d',
    messagingSenderId: '908484753448',
    projectId: 'whatsapp-clone-95d94',
    authDomain: 'whatsapp-clone-95d94.firebaseapp.com',
    storageBucket: 'whatsapp-clone-95d94.appspot.com',
    measurementId: 'G-V4T770BZFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlMgae0NZnqfweWh6B8HeP4rHpiRqHHjM',
    appId: '1:908484753448:android:32768c174774e4c5be5d1d',
    messagingSenderId: '908484753448',
    projectId: 'whatsapp-clone-95d94',
    storageBucket: 'whatsapp-clone-95d94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwtf3NDSKXL3j9P8bkzms7pf96mYMvju4',
    appId: '1:908484753448:ios:1053b8df7720d7c7be5d1d',
    messagingSenderId: '908484753448',
    projectId: 'whatsapp-clone-95d94',
    storageBucket: 'whatsapp-clone-95d94.appspot.com',
    iosClientId: '908484753448-pri65e5uuvbtk5dh9u1eqdh04mu4n5ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwtf3NDSKXL3j9P8bkzms7pf96mYMvju4',
    appId: '1:908484753448:ios:1053b8df7720d7c7be5d1d',
    messagingSenderId: '908484753448',
    projectId: 'whatsapp-clone-95d94',
    storageBucket: 'whatsapp-clone-95d94.appspot.com',
    iosClientId: '908484753448-pri65e5uuvbtk5dh9u1eqdh04mu4n5ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
